### ISSUE TITLE
std::system_error thrown 

### ISSUE THREAD

**Issue by mdmarshmallow** [RoboJackets/stsl#15]
Code
```
#include <STSL/RJRobot.h>
#include <iostream>

using namespace std;

bool isBlack(RJRobot robot) {
    int  line_sensor = robot.GetLineValue(LineSensor::CENTER);
    if (line_sensor > 1500) {
        return true;
    } else {
        return false;
    }
}

int main() {
    RJRobot robot(RobotType::REAL);

    // your code here
    while (true) {
        if (isBlack(robot)) {
            robot.SetDriveMotors(150, 100);
        } else {
            robot.SetDriveMotors(100, 150);
        }
    }

    return 0;
}
```

Terminal output:
>Initializing...
>Looking for a real robot.
>Robot ready!
>terminate called after throwing an instance of 'std::system_error'
>  what():  send failed: Unknown error
>
>Process finished with exit code 3

**Comment by barulicm** [comment]
Hi!
Can you let me know what operating system you're running?
Then, are you connected to the robot's wifi network (RJ_TRAINII_*)? If so, can you "see" the robot on the network?
Try:
`ping 10.10.10.1`

**Comment by JasonGibson274** [comment]
I am a big dumb the method does not pass by reference so it is not an initialized version of the RJRobot object. We should improve the error message they get.

**Comment by barulicm** [comment]
Mmm I see. Hadn't noticed the function.
RJRobot should probably not be copyable. I can create an issue for that.

**Comment by JasonGibson274** [comment]
I mean perfect example for why references are useful.
