### ISSUE TITLE
Properly manage windows devices

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/stsl#9]

**Comment by jgkamat** [comment]
I think the relevant code snippet for this is [here](https://github.com/RoboJackets/stsl/blob/ec08609c3478e4d343fe90aac92370d7550d0bce/src/WindowsUtils.cpp#L10), a simple fix would be to let the user pass in the index and guess the correct one.

**Comment by barulicm** [comment]
Closing this as it is not relevant to the new WiFi-based system.
